/*
 * generated by Xtext 2.40.0
 */
package gameOfLife.tasks.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TaskDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("gameOfLife/tasks/parser/antlr/internal/InternalTaskDSL.tokens");
	}
}
