/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.taskDSL.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import persons.tasks.taskDSL.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see persons.tasks.taskDSL.TaskDSLPackage
 * @generated
 */
public class TaskDSLAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static TaskDSLPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TaskDSLAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = TaskDSLPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TaskDSLSwitch<Adapter> modelSwitch =
    new TaskDSLSwitch<Adapter>()
    {
      @Override
      public Adapter casePlanning(Planning object)
      {
        return createPlanningAdapter();
      }
      @Override
      public Adapter casePersonTasks(PersonTasks object)
      {
        return createPersonTasksAdapter();
      }
      @Override
      public Adapter caseTask(Task object)
      {
        return createTaskAdapter();
      }
      @Override
      public Adapter caseAction(Action object)
      {
        return createActionAdapter();
      }
      @Override
      public Adapter caseLunchAction(LunchAction object)
      {
        return createLunchActionAdapter();
      }
      @Override
      public Adapter caseMeetingAction(MeetingAction object)
      {
        return createMeetingActionAdapter();
      }
      @Override
      public Adapter casePaperAction(PaperAction object)
      {
        return createPaperActionAdapter();
      }
      @Override
      public Adapter casePaymentAction(PaymentAction object)
      {
        return createPaymentActionAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.Planning <em>Planning</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.Planning
   * @generated
   */
  public Adapter createPlanningAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.PersonTasks <em>Person Tasks</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.PersonTasks
   * @generated
   */
  public Adapter createPersonTasksAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.Task
   * @generated
   */
  public Adapter createTaskAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.Action
   * @generated
   */
  public Adapter createActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.LunchAction <em>Lunch Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.LunchAction
   * @generated
   */
  public Adapter createLunchActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.MeetingAction <em>Meeting Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.MeetingAction
   * @generated
   */
  public Adapter createMeetingActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.PaperAction <em>Paper Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.PaperAction
   * @generated
   */
  public Adapter createPaperActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link persons.tasks.taskDSL.PaymentAction <em>Payment Action</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see persons.tasks.taskDSL.PaymentAction
   * @generated
   */
  public Adapter createPaymentActionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //TaskDSLAdapterFactory
