/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import gameoflife.dsl.ide.contentassist.antlr.internal.InternalGameOfLifeDSLParser;
import gameoflife.dsl.services.GameOfLifeDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GameOfLifeDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GameOfLifeDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GameOfLifeDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNeighborConditionAccess().getAlternatives(), "rule__NeighborCondition__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getGridAccess().getGroup(), "rule__Grid__Group__0");
			builder.put(grammarAccess.getCellAccess().getGroup(), "rule__Cell__Group__0");
			builder.put(grammarAccess.getRulesAccess().getGroup(), "rule__Rules__Group__0");
			builder.put(grammarAccess.getSurviveRuleAccess().getGroup(), "rule__SurviveRule__Group__0");
			builder.put(grammarAccess.getBirthRuleAccess().getGroup(), "rule__BirthRule__Group__0");
			builder.put(grammarAccess.getRangeAccess().getGroup(), "rule__Range__Group__0");
			builder.put(grammarAccess.getModelAccess().getGridsAssignment_0(), "rule__Model__GridsAssignment_0");
			builder.put(grammarAccess.getModelAccess().getRulesAssignment_1(), "rule__Model__RulesAssignment_1");
			builder.put(grammarAccess.getGridAccess().getNameAssignment_1(), "rule__Grid__NameAssignment_1");
			builder.put(grammarAccess.getGridAccess().getLiveCellsAssignment_3(), "rule__Grid__LiveCellsAssignment_3");
			builder.put(grammarAccess.getCellAccess().getXAssignment_2(), "rule__Cell__XAssignment_2");
			builder.put(grammarAccess.getCellAccess().getYAssignment_4(), "rule__Cell__YAssignment_4");
			builder.put(grammarAccess.getRulesAccess().getSurviveRulesAssignment_2(), "rule__Rules__SurviveRulesAssignment_2");
			builder.put(grammarAccess.getRulesAccess().getBirthRulesAssignment_3(), "rule__Rules__BirthRulesAssignment_3");
			builder.put(grammarAccess.getSurviveRuleAccess().getNeighborsAssignment_2(), "rule__SurviveRule__NeighborsAssignment_2");
			builder.put(grammarAccess.getBirthRuleAccess().getNeighborsAssignment_2(), "rule__BirthRule__NeighborsAssignment_2");
			builder.put(grammarAccess.getNeighborConditionAccess().getCountAssignment_0(), "rule__NeighborCondition__CountAssignment_0");
			builder.put(grammarAccess.getNeighborConditionAccess().getRangeAssignment_1(), "rule__NeighborCondition__RangeAssignment_1");
			builder.put(grammarAccess.getRangeAccess().getMinAssignment_1(), "rule__Range__MinAssignment_1");
			builder.put(grammarAccess.getRangeAccess().getMaxAssignment_3(), "rule__Range__MaxAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GameOfLifeDSLGrammarAccess grammarAccess;

	@Override
	protected InternalGameOfLifeDSLParser createParser() {
		InternalGameOfLifeDSLParser result = new InternalGameOfLifeDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameOfLifeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameOfLifeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
