/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GameOfLifeDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("gameoflife/dsl/parser/antlr/internal/InternalGameOfLifeDSL.tokens");
	}
}
