/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.ui.tests;

import com.google.inject.Injector;
import gameoflife.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GameOfLifeDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("gameoflife.dsl.GameOfLifeDSL");
	}

}
