/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GameOfLifeDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cGridsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cGridsGridParserRuleCall_0_0 = (RuleCall)cGridsAssignment_0.eContents().get(0);
		private final Assignment cRulesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRulesRulesParserRuleCall_1_0 = (RuleCall)cRulesAssignment_1.eContents().get(0);
		
		//Model:
		//    (grids += Grid)*
		//    (rules += Rules)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(grids += Grid)*
		//(rules += Rules)?
		public Group getGroup() { return cGroup; }
		
		//(grids += Grid)*
		public Assignment getGridsAssignment_0() { return cGridsAssignment_0; }
		
		//Grid
		public RuleCall getGridsGridParserRuleCall_0_0() { return cGridsGridParserRuleCall_0_0; }
		
		//(rules += Rules)?
		public Assignment getRulesAssignment_1() { return cRulesAssignment_1; }
		
		//Rules
		public RuleCall getRulesRulesParserRuleCall_1_0() { return cRulesRulesParserRuleCall_1_0; }
	}
	public class GridElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.Grid");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGridKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLiveCellsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLiveCellsCellParserRuleCall_3_0 = (RuleCall)cLiveCellsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Grid:
		//    'grid' name=ID '{'
		//        (liveCells += Cell)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'grid' name=ID '{'
		//    (liveCells += Cell)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'grid'
		public Keyword getGridKeyword_0() { return cGridKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(liveCells += Cell)*
		public Assignment getLiveCellsAssignment_3() { return cLiveCellsAssignment_3; }
		
		//Cell
		public RuleCall getLiveCellsCellParserRuleCall_3_0() { return cLiveCellsCellParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class CellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.Cell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCellKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXINTTerminalRuleCall_2_0 = (RuleCall)cXAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYINTTerminalRuleCall_4_0 = (RuleCall)cYAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Cell:
		//    'cell' '(' x=INT ',' y=INT ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'cell' '(' x=INT ',' y=INT ')'
		public Group getGroup() { return cGroup; }
		
		//'cell'
		public Keyword getCellKeyword_0() { return cCellKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//x=INT
		public Assignment getXAssignment_2() { return cXAssignment_2; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_2_0() { return cXINTTerminalRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//y=INT
		public Assignment getYAssignment_4() { return cYAssignment_4; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_4_0() { return cYINTTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class RulesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.Rules");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRulesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSurviveRulesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSurviveRulesSurviveRuleParserRuleCall_2_0 = (RuleCall)cSurviveRulesAssignment_2.eContents().get(0);
		private final Assignment cBirthRulesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBirthRulesBirthRuleParserRuleCall_3_0 = (RuleCall)cBirthRulesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Rules:
		//    'rules' '{'
		//        surviveRules += SurviveRule*
		//        birthRules += BirthRule*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'rules' '{'
		//    surviveRules += SurviveRule*
		//    birthRules += BirthRule*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'rules'
		public Keyword getRulesKeyword_0() { return cRulesKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//surviveRules += SurviveRule*
		public Assignment getSurviveRulesAssignment_2() { return cSurviveRulesAssignment_2; }
		
		//SurviveRule
		public RuleCall getSurviveRulesSurviveRuleParserRuleCall_2_0() { return cSurviveRulesSurviveRuleParserRuleCall_2_0; }
		
		//birthRules += BirthRule*
		public Assignment getBirthRulesAssignment_3() { return cBirthRulesAssignment_3; }
		
		//BirthRule
		public RuleCall getBirthRulesBirthRuleParserRuleCall_3_0() { return cBirthRulesBirthRuleParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SurviveRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.SurviveRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSurviveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWhenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNeighborsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNeighborsNeighborConditionParserRuleCall_2_0 = (RuleCall)cNeighborsAssignment_2.eContents().get(0);
		
		//SurviveRule:
		//    'survive' 'when' neighbors=NeighborCondition
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'survive' 'when' neighbors=NeighborCondition
		public Group getGroup() { return cGroup; }
		
		//'survive'
		public Keyword getSurviveKeyword_0() { return cSurviveKeyword_0; }
		
		//'when'
		public Keyword getWhenKeyword_1() { return cWhenKeyword_1; }
		
		//neighbors=NeighborCondition
		public Assignment getNeighborsAssignment_2() { return cNeighborsAssignment_2; }
		
		//NeighborCondition
		public RuleCall getNeighborsNeighborConditionParserRuleCall_2_0() { return cNeighborsNeighborConditionParserRuleCall_2_0; }
	}
	public class BirthRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.BirthRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBirthKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWhenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNeighborsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNeighborsNeighborConditionParserRuleCall_2_0 = (RuleCall)cNeighborsAssignment_2.eContents().get(0);
		
		//BirthRule:
		//    'birth' 'when' neighbors=NeighborCondition
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'birth' 'when' neighbors=NeighborCondition
		public Group getGroup() { return cGroup; }
		
		//'birth'
		public Keyword getBirthKeyword_0() { return cBirthKeyword_0; }
		
		//'when'
		public Keyword getWhenKeyword_1() { return cWhenKeyword_1; }
		
		//neighbors=NeighborCondition
		public Assignment getNeighborsAssignment_2() { return cNeighborsAssignment_2; }
		
		//NeighborCondition
		public RuleCall getNeighborsNeighborConditionParserRuleCall_2_0() { return cNeighborsNeighborConditionParserRuleCall_2_0; }
	}
	public class NeighborConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.NeighborCondition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cCountAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cCountINTTerminalRuleCall_0_0 = (RuleCall)cCountAssignment_0.eContents().get(0);
		private final Assignment cRangeAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cRangeRangeParserRuleCall_1_0 = (RuleCall)cRangeAssignment_1.eContents().get(0);
		
		//NeighborCondition:
		//    count=INT
		//    | range=Range
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//count=INT
		//| range=Range
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//count=INT
		public Assignment getCountAssignment_0() { return cCountAssignment_0; }
		
		//INT
		public RuleCall getCountINTTerminalRuleCall_0_0() { return cCountINTTerminalRuleCall_0_0; }
		
		//range=Range
		public Assignment getRangeAssignment_1() { return cRangeAssignment_1; }
		
		//Range
		public RuleCall getRangeRangeParserRuleCall_1_0() { return cRangeRangeParserRuleCall_1_0; }
	}
	public class RangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "gameoflife.dsl.GameOfLifeDSL.Range");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMinAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMinINTTerminalRuleCall_1_0 = (RuleCall)cMinAssignment_1.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMaxAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMaxINTTerminalRuleCall_3_0 = (RuleCall)cMaxAssignment_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Range:
		//    '[' min=INT '..' max=INT ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'[' min=INT '..' max=INT ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//min=INT
		public Assignment getMinAssignment_1() { return cMinAssignment_1; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_1_0() { return cMinINTTerminalRuleCall_1_0; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_2() { return cFullStopFullStopKeyword_2; }
		
		//max=INT
		public Assignment getMaxAssignment_3() { return cMaxAssignment_3; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_3_0() { return cMaxINTTerminalRuleCall_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}
	
	
	private final ModelElements pModel;
	private final GridElements pGrid;
	private final CellElements pCell;
	private final RulesElements pRules;
	private final SurviveRuleElements pSurviveRule;
	private final BirthRuleElements pBirthRule;
	private final NeighborConditionElements pNeighborCondition;
	private final RangeElements pRange;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GameOfLifeDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pGrid = new GridElements();
		this.pCell = new CellElements();
		this.pRules = new RulesElements();
		this.pSurviveRule = new SurviveRuleElements();
		this.pBirthRule = new BirthRuleElements();
		this.pNeighborCondition = new NeighborConditionElements();
		this.pRange = new RangeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("gameoflife.dsl.GameOfLifeDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    (grids += Grid)*
	//    (rules += Rules)?
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Grid:
	//    'grid' name=ID '{'
	//        (liveCells += Cell)*
	//    '}'
	//;
	public GridElements getGridAccess() {
		return pGrid;
	}
	
	public ParserRule getGridRule() {
		return getGridAccess().getRule();
	}
	
	//Cell:
	//    'cell' '(' x=INT ',' y=INT ')'
	//;
	public CellElements getCellAccess() {
		return pCell;
	}
	
	public ParserRule getCellRule() {
		return getCellAccess().getRule();
	}
	
	//Rules:
	//    'rules' '{'
	//        surviveRules += SurviveRule*
	//        birthRules += BirthRule*
	//    '}'
	//;
	public RulesElements getRulesAccess() {
		return pRules;
	}
	
	public ParserRule getRulesRule() {
		return getRulesAccess().getRule();
	}
	
	//SurviveRule:
	//    'survive' 'when' neighbors=NeighborCondition
	//;
	public SurviveRuleElements getSurviveRuleAccess() {
		return pSurviveRule;
	}
	
	public ParserRule getSurviveRuleRule() {
		return getSurviveRuleAccess().getRule();
	}
	
	//BirthRule:
	//    'birth' 'when' neighbors=NeighborCondition
	//;
	public BirthRuleElements getBirthRuleAccess() {
		return pBirthRule;
	}
	
	public ParserRule getBirthRuleRule() {
		return getBirthRuleAccess().getRule();
	}
	
	//NeighborCondition:
	//    count=INT
	//    | range=Range
	//;
	public NeighborConditionElements getNeighborConditionAccess() {
		return pNeighborCondition;
	}
	
	public ParserRule getNeighborConditionRule() {
		return getNeighborConditionAccess().getRule();
	}
	
	//Range:
	//    '[' min=INT '..' max=INT ']'
	//;
	public RangeElements getRangeAccess() {
		return pRange;
	}
	
	public ParserRule getRangeRule() {
		return getRangeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
