/*
 * generated by Xtext 2.40.0
 */
package gameOfLife.tasks.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TaskDSLProposalProvider extends AbstractTaskDSLProposalProvider {
}
