/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class GameOfLifeDSLScopeProvider extends AbstractGameOfLifeDSLScopeProvider {

}
