/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameOfLifeDSLStandaloneSetup extends GameOfLifeDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new GameOfLifeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
