/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameOfLifeDSLRuntimeModule extends AbstractGameOfLifeDSLRuntimeModule {
}
