/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameOfLifeDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameOfLifeDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.dsl.gameoflife/GameOfLifeDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameOfLifeDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameOfLifeDSLPackage eINSTANCE = gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.ModelImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Grids</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GRIDS = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__RULES = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GridImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getGrid()
   * @generated
   */
  int GRID = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__NAME = 0;

  /**
   * The feature id for the '<em><b>Live Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__LIVE_CELLS = 1;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.CellImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 2;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__Y = 1;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.RulesImpl <em>Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.RulesImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getRules()
   * @generated
   */
  int RULES = 3;

  /**
   * The feature id for the '<em><b>Survive Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__SURVIVE_RULES = 0;

  /**
   * The feature id for the '<em><b>Birth Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__BIRTH_RULES = 1;

  /**
   * The number of structural features of the '<em>Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.SurviveRuleImpl <em>Survive Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.SurviveRuleImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getSurviveRule()
   * @generated
   */
  int SURVIVE_RULE = 4;

  /**
   * The feature id for the '<em><b>Neighbors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURVIVE_RULE__NEIGHBORS = 0;

  /**
   * The number of structural features of the '<em>Survive Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURVIVE_RULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.BirthRuleImpl <em>Birth Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.BirthRuleImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getBirthRule()
   * @generated
   */
  int BIRTH_RULE = 5;

  /**
   * The feature id for the '<em><b>Neighbors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIRTH_RULE__NEIGHBORS = 0;

  /**
   * The number of structural features of the '<em>Birth Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIRTH_RULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.NeighborConditionImpl <em>Neighbor Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.NeighborConditionImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getNeighborCondition()
   * @generated
   */
  int NEIGHBOR_CONDITION = 6;

  /**
   * The feature id for the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEIGHBOR_CONDITION__COUNT = 0;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEIGHBOR_CONDITION__RANGE = 1;

  /**
   * The number of structural features of the '<em>Neighbor Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEIGHBOR_CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.dsl.gameOfLifeDSL.impl.RangeImpl
   * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getRange()
   * @generated
   */
  int RANGE = 7;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__MIN = 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__MAX = 1;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.dsl.gameOfLifeDSL.Model#getGrids <em>Grids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Grids</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Model#getGrids()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Grids();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.dsl.gameOfLifeDSL.Model#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Model#getRules()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Rules();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.dsl.gameOfLifeDSL.Grid#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Grid#getName()
   * @see #getGrid()
   * @generated
   */
  EAttribute getGrid_Name();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.dsl.gameOfLifeDSL.Grid#getLiveCells <em>Live Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Live Cells</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Grid#getLiveCells()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_LiveCells();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.dsl.gameOfLifeDSL.Cell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Cell#getX()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_X();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.dsl.gameOfLifeDSL.Cell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Cell#getY()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Y();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.Rules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Rules
   * @generated
   */
  EClass getRules();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.dsl.gameOfLifeDSL.Rules#getSurviveRules <em>Survive Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Survive Rules</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Rules#getSurviveRules()
   * @see #getRules()
   * @generated
   */
  EReference getRules_SurviveRules();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.dsl.gameOfLifeDSL.Rules#getBirthRules <em>Birth Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Birth Rules</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Rules#getBirthRules()
   * @see #getRules()
   * @generated
   */
  EReference getRules_BirthRules();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.SurviveRule <em>Survive Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Survive Rule</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.SurviveRule
   * @generated
   */
  EClass getSurviveRule();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.dsl.gameOfLifeDSL.SurviveRule#getNeighbors <em>Neighbors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Neighbors</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.SurviveRule#getNeighbors()
   * @see #getSurviveRule()
   * @generated
   */
  EReference getSurviveRule_Neighbors();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.BirthRule <em>Birth Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Birth Rule</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.BirthRule
   * @generated
   */
  EClass getBirthRule();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.dsl.gameOfLifeDSL.BirthRule#getNeighbors <em>Neighbors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Neighbors</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.BirthRule#getNeighbors()
   * @see #getBirthRule()
   * @generated
   */
  EReference getBirthRule_Neighbors();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition <em>Neighbor Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Neighbor Condition</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.NeighborCondition
   * @generated
   */
  EClass getNeighborCondition();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getCount()
   * @see #getNeighborCondition()
   * @generated
   */
  EAttribute getNeighborCondition_Count();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getRange()
   * @see #getNeighborCondition()
   * @generated
   */
  EReference getNeighborCondition_Range();

  /**
   * Returns the meta object for class '{@link gameoflife.dsl.gameOfLifeDSL.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.dsl.gameOfLifeDSL.Range#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Range#getMin()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Min();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.dsl.gameOfLifeDSL.Range#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see gameoflife.dsl.gameOfLifeDSL.Range#getMax()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Max();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameOfLifeDSLFactory getGameOfLifeDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.ModelImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Grids</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GRIDS = eINSTANCE.getModel_Grids();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__RULES = eINSTANCE.getModel_Rules();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GridImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID__NAME = eINSTANCE.getGrid_Name();

    /**
     * The meta object literal for the '<em><b>Live Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__LIVE_CELLS = eINSTANCE.getGrid_LiveCells();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.CellImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__X = eINSTANCE.getCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__Y = eINSTANCE.getCell_Y();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.RulesImpl <em>Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.RulesImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getRules()
     * @generated
     */
    EClass RULES = eINSTANCE.getRules();

    /**
     * The meta object literal for the '<em><b>Survive Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__SURVIVE_RULES = eINSTANCE.getRules_SurviveRules();

    /**
     * The meta object literal for the '<em><b>Birth Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__BIRTH_RULES = eINSTANCE.getRules_BirthRules();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.SurviveRuleImpl <em>Survive Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.SurviveRuleImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getSurviveRule()
     * @generated
     */
    EClass SURVIVE_RULE = eINSTANCE.getSurviveRule();

    /**
     * The meta object literal for the '<em><b>Neighbors</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SURVIVE_RULE__NEIGHBORS = eINSTANCE.getSurviveRule_Neighbors();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.BirthRuleImpl <em>Birth Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.BirthRuleImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getBirthRule()
     * @generated
     */
    EClass BIRTH_RULE = eINSTANCE.getBirthRule();

    /**
     * The meta object literal for the '<em><b>Neighbors</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BIRTH_RULE__NEIGHBORS = eINSTANCE.getBirthRule_Neighbors();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.NeighborConditionImpl <em>Neighbor Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.NeighborConditionImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getNeighborCondition()
     * @generated
     */
    EClass NEIGHBOR_CONDITION = eINSTANCE.getNeighborCondition();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NEIGHBOR_CONDITION__COUNT = eINSTANCE.getNeighborCondition_Count();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEIGHBOR_CONDITION__RANGE = eINSTANCE.getNeighborCondition_Range();

    /**
     * The meta object literal for the '{@link gameoflife.dsl.gameOfLifeDSL.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.dsl.gameOfLifeDSL.impl.RangeImpl
     * @see gameoflife.dsl.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__MIN = eINSTANCE.getRange_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__MAX = eINSTANCE.getRange_Max();

  }

} //GameOfLifeDSLPackage
