/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.Model#getGrids <em>Grids</em>}</li>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.Model#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Grids</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.dsl.gameOfLifeDSL.Grid}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grids</em>' containment reference list.
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getModel_Grids()
   * @model containment="true"
   * @generated
   */
  EList<Grid> getGrids();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.dsl.gameOfLifeDSL.Rules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getModel_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rules> getRules();

} // Model
