/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Neighbor Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getCount <em>Count</em>}</li>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getNeighborCondition()
 * @model
 * @generated
 */
public interface NeighborCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(int)
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getNeighborCondition_Count()
   * @model
   * @generated
   */
  int getCount();

  /**
   * Sets the value of the '{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(int value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(Range)
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getNeighborCondition_Range()
   * @model containment="true"
   * @generated
   */
  Range getRange();

  /**
   * Sets the value of the '{@link gameoflife.dsl.gameOfLifeDSL.NeighborCondition#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(Range value);

} // NeighborCondition
