/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.Range#getMin <em>Min</em>}</li>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.Range#getMax <em>Max</em>}</li>
 * </ul>
 *
 * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute.
   * @see #setMin(int)
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getRange_Min()
   * @model
   * @generated
   */
  int getMin();

  /**
   * Sets the value of the '{@link gameoflife.dsl.gameOfLifeDSL.Range#getMin <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min</em>' attribute.
   * @see #getMin()
   * @generated
   */
  void setMin(int value);

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getRange_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link gameoflife.dsl.gameOfLifeDSL.Range#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

} // Range
