/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.Rules#getSurviveRules <em>Survive Rules</em>}</li>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.Rules#getBirthRules <em>Birth Rules</em>}</li>
 * </ul>
 *
 * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getRules()
 * @model
 * @generated
 */
public interface Rules extends EObject
{
  /**
   * Returns the value of the '<em><b>Survive Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.dsl.gameOfLifeDSL.SurviveRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Survive Rules</em>' containment reference list.
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getRules_SurviveRules()
   * @model containment="true"
   * @generated
   */
  EList<SurviveRule> getSurviveRules();

  /**
   * Returns the value of the '<em><b>Birth Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.dsl.gameOfLifeDSL.BirthRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Birth Rules</em>' containment reference list.
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getRules_BirthRules()
   * @model containment="true"
   * @generated
   */
  EList<BirthRule> getBirthRules();

} // Rules
