/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Survive Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.SurviveRule#getNeighbors <em>Neighbors</em>}</li>
 * </ul>
 *
 * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getSurviveRule()
 * @model
 * @generated
 */
public interface SurviveRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Neighbors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neighbors</em>' containment reference.
   * @see #setNeighbors(NeighborCondition)
   * @see gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage#getSurviveRule_Neighbors()
   * @model containment="true"
   * @generated
   */
  NeighborCondition getNeighbors();

  /**
   * Sets the value of the '{@link gameoflife.dsl.gameOfLifeDSL.SurviveRule#getNeighbors <em>Neighbors</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neighbors</em>' containment reference.
   * @see #getNeighbors()
   * @generated
   */
  void setNeighbors(NeighborCondition value);

} // SurviveRule
