/*
 * generated by Xtext 2.40.0
 */
package gameOfLife.tasks.ui.tests;

import com.google.inject.Injector;
import gameOfLife.tasks.ui.internal.TasksActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TaskDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TasksActivator.getInstance().getInjector("gameOfLife.tasks.TaskDSL");
	}

}
