/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameOfLifeDSLScopeProvider extends DelegatingScopeProvider {
}
