/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL.impl;

import gameoflife.dsl.gameOfLifeDSL.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GameOfLifeDSLFactoryImpl extends EFactoryImpl implements GameOfLifeDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GameOfLifeDSLFactory init()
  {
    try
    {
      GameOfLifeDSLFactory theGameOfLifeDSLFactory = (GameOfLifeDSLFactory)EPackage.Registry.INSTANCE.getEFactory(GameOfLifeDSLPackage.eNS_URI);
      if (theGameOfLifeDSLFactory != null)
      {
        return theGameOfLifeDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GameOfLifeDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GameOfLifeDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GameOfLifeDSLPackage.MODEL: return createModel();
      case GameOfLifeDSLPackage.GRID: return createGrid();
      case GameOfLifeDSLPackage.CELL: return createCell();
      case GameOfLifeDSLPackage.RULES: return createRules();
      case GameOfLifeDSLPackage.SURVIVE_RULE: return createSurviveRule();
      case GameOfLifeDSLPackage.BIRTH_RULE: return createBirthRule();
      case GameOfLifeDSLPackage.NEIGHBOR_CONDITION: return createNeighborCondition();
      case GameOfLifeDSLPackage.RANGE: return createRange();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Grid createGrid()
  {
    GridImpl grid = new GridImpl();
    return grid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cell createCell()
  {
    CellImpl cell = new CellImpl();
    return cell;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rules createRules()
  {
    RulesImpl rules = new RulesImpl();
    return rules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SurviveRule createSurviveRule()
  {
    SurviveRuleImpl surviveRule = new SurviveRuleImpl();
    return surviveRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BirthRule createBirthRule()
  {
    BirthRuleImpl birthRule = new BirthRuleImpl();
    return birthRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NeighborCondition createNeighborCondition()
  {
    NeighborConditionImpl neighborCondition = new NeighborConditionImpl();
    return neighborCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Range createRange()
  {
    RangeImpl range = new RangeImpl();
    return range;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GameOfLifeDSLPackage getGameOfLifeDSLPackage()
  {
    return (GameOfLifeDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GameOfLifeDSLPackage getPackage()
  {
    return GameOfLifeDSLPackage.eINSTANCE;
  }

} //GameOfLifeDSLFactoryImpl
