/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL.impl;

import gameoflife.dsl.gameOfLifeDSL.BirthRule;
import gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage;
import gameoflife.dsl.gameOfLifeDSL.Rules;
import gameoflife.dsl.gameOfLifeDSL.SurviveRule;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rules</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.impl.RulesImpl#getSurviveRules <em>Survive Rules</em>}</li>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.impl.RulesImpl#getBirthRules <em>Birth Rules</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RulesImpl extends MinimalEObjectImpl.Container implements Rules
{
  /**
   * The cached value of the '{@link #getSurviveRules() <em>Survive Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSurviveRules()
   * @generated
   * @ordered
   */
  protected EList<SurviveRule> surviveRules;

  /**
   * The cached value of the '{@link #getBirthRules() <em>Birth Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBirthRules()
   * @generated
   * @ordered
   */
  protected EList<BirthRule> birthRules;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameOfLifeDSLPackage.Literals.RULES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SurviveRule> getSurviveRules()
  {
    if (surviveRules == null)
    {
      surviveRules = new EObjectContainmentEList<SurviveRule>(SurviveRule.class, this, GameOfLifeDSLPackage.RULES__SURVIVE_RULES);
    }
    return surviveRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BirthRule> getBirthRules()
  {
    if (birthRules == null)
    {
      birthRules = new EObjectContainmentEList<BirthRule>(BirthRule.class, this, GameOfLifeDSLPackage.RULES__BIRTH_RULES);
    }
    return birthRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.RULES__SURVIVE_RULES:
        return ((InternalEList<?>)getSurviveRules()).basicRemove(otherEnd, msgs);
      case GameOfLifeDSLPackage.RULES__BIRTH_RULES:
        return ((InternalEList<?>)getBirthRules()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.RULES__SURVIVE_RULES:
        return getSurviveRules();
      case GameOfLifeDSLPackage.RULES__BIRTH_RULES:
        return getBirthRules();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.RULES__SURVIVE_RULES:
        getSurviveRules().clear();
        getSurviveRules().addAll((Collection<? extends SurviveRule>)newValue);
        return;
      case GameOfLifeDSLPackage.RULES__BIRTH_RULES:
        getBirthRules().clear();
        getBirthRules().addAll((Collection<? extends BirthRule>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.RULES__SURVIVE_RULES:
        getSurviveRules().clear();
        return;
      case GameOfLifeDSLPackage.RULES__BIRTH_RULES:
        getBirthRules().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.RULES__SURVIVE_RULES:
        return surviveRules != null && !surviveRules.isEmpty();
      case GameOfLifeDSLPackage.RULES__BIRTH_RULES:
        return birthRules != null && !birthRules.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RulesImpl
