/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.gameOfLifeDSL.impl;

import gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage;
import gameoflife.dsl.gameOfLifeDSL.NeighborCondition;
import gameoflife.dsl.gameOfLifeDSL.SurviveRule;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Survive Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.dsl.gameOfLifeDSL.impl.SurviveRuleImpl#getNeighbors <em>Neighbors</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SurviveRuleImpl extends MinimalEObjectImpl.Container implements SurviveRule
{
  /**
   * The cached value of the '{@link #getNeighbors() <em>Neighbors</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeighbors()
   * @generated
   * @ordered
   */
  protected NeighborCondition neighbors;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SurviveRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameOfLifeDSLPackage.Literals.SURVIVE_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NeighborCondition getNeighbors()
  {
    return neighbors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNeighbors(NeighborCondition newNeighbors, NotificationChain msgs)
  {
    NeighborCondition oldNeighbors = neighbors;
    neighbors = newNeighbors;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS, oldNeighbors, newNeighbors);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNeighbors(NeighborCondition newNeighbors)
  {
    if (newNeighbors != neighbors)
    {
      NotificationChain msgs = null;
      if (neighbors != null)
        msgs = ((InternalEObject)neighbors).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS, null, msgs);
      if (newNeighbors != null)
        msgs = ((InternalEObject)newNeighbors).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS, null, msgs);
      msgs = basicSetNeighbors(newNeighbors, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS, newNeighbors, newNeighbors));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS:
        return basicSetNeighbors(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS:
        return getNeighbors();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS:
        setNeighbors((NeighborCondition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS:
        setNeighbors((NeighborCondition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameOfLifeDSLPackage.SURVIVE_RULE__NEIGHBORS:
        return neighbors != null;
    }
    return super.eIsSet(featureID);
  }

} //SurviveRuleImpl
