/*
 * generated by Xtext 2.40.0
 */
package gameOfLife.tasks;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TaskDSLRuntimeModule extends AbstractTaskDSLRuntimeModule {
}
