/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person Tasks</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks.taskDSL.PersonTasks#getName <em>Name</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.PersonTasks#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see persons.tasks.taskDSL.TaskDSLPackage#getPersonTasks()
 * @model
 * @generated
 */
public interface PersonTasks extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getPersonTasks_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.PersonTasks#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link persons.tasks.taskDSL.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see persons.tasks.taskDSL.TaskDSLPackage#getPersonTasks_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // PersonTasks
