/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Planning</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks.taskDSL.Planning#getPersonlist <em>Personlist</em>}</li>
 * </ul>
 *
 * @see persons.tasks.taskDSL.TaskDSLPackage#getPlanning()
 * @model
 * @generated
 */
public interface Planning extends EObject
{
  /**
   * Returns the value of the '<em><b>Personlist</b></em>' containment reference list.
   * The list contents are of type {@link persons.tasks.taskDSL.PersonTasks}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Personlist</em>' containment reference list.
   * @see persons.tasks.taskDSL.TaskDSLPackage#getPlanning_Personlist()
   * @model containment="true"
   * @generated
   */
  EList<PersonTasks> getPersonlist();

} // Planning
