/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see persons.tasks.taskDSL.TaskDSLPackage
 * @generated
 */
public interface TaskDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TaskDSLFactory eINSTANCE = persons.tasks.taskDSL.impl.TaskDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Planning</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Planning</em>'.
   * @generated
   */
  Planning createPlanning();

  /**
   * Returns a new object of class '<em>Person Tasks</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person Tasks</em>'.
   * @generated
   */
  PersonTasks createPersonTasks();

  /**
   * Returns a new object of class '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task</em>'.
   * @generated
   */
  Task createTask();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Lunch Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lunch Action</em>'.
   * @generated
   */
  LunchAction createLunchAction();

  /**
   * Returns a new object of class '<em>Meeting Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Meeting Action</em>'.
   * @generated
   */
  MeetingAction createMeetingAction();

  /**
   * Returns a new object of class '<em>Paper Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Paper Action</em>'.
   * @generated
   */
  PaperAction createPaperAction();

  /**
   * Returns a new object of class '<em>Payment Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Payment Action</em>'.
   * @generated
   */
  PaymentAction createPaymentAction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TaskDSLPackage getTaskDSLPackage();

} //TaskDSLFactory
