/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see persons.tasks.taskDSL.TaskDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TaskDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "taskDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tasks.persons/TaskDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "taskDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TaskDSLPackage eINSTANCE = persons.tasks.taskDSL.impl.TaskDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PlanningImpl <em>Planning</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PlanningImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPlanning()
   * @generated
   */
  int PLANNING = 0;

  /**
   * The feature id for the '<em><b>Personlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__PERSONLIST = 0;

  /**
   * The number of structural features of the '<em>Planning</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PersonTasksImpl <em>Person Tasks</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PersonTasksImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPersonTasks()
   * @generated
   */
  int PERSON_TASKS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_TASKS__NAME = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_TASKS__TASKS = 1;

  /**
   * The number of structural features of the '<em>Person Tasks</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_TASKS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.TaskImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTION = 0;

  /**
   * The feature id for the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIO = 1;

  /**
   * The feature id for the '<em><b>Dl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DL = 2;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__UNIT = 3;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.LunchActionImpl <em>Lunch Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.LunchActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getLunchAction()
   * @generated
   */
  int LUNCH_ACTION = 4;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_ACTION__LOCATION = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lunch Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.MeetingActionImpl <em>Meeting Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.MeetingActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getMeetingAction()
   * @generated
   */
  int MEETING_ACTION = 5;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEETING_ACTION__TOPIC = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Meeting Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEETING_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PaperActionImpl <em>Paper Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PaperActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaperAction()
   * @generated
   */
  int PAPER_ACTION = 6;

  /**
   * The feature id for the '<em><b>Report</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAPER_ACTION__REPORT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Paper Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAPER_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PaymentActionImpl <em>Payment Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PaymentActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaymentAction()
   * @generated
   */
  int PAYMENT_ACTION = 7;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION__AMOUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Payment Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.TimeUnit <em>Time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.TimeUnit
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 8;


  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Planning <em>Planning</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Planning</em>'.
   * @see persons.tasks.taskDSL.Planning
   * @generated
   */
  EClass getPlanning();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks.taskDSL.Planning#getPersonlist <em>Personlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Personlist</em>'.
   * @see persons.tasks.taskDSL.Planning#getPersonlist()
   * @see #getPlanning()
   * @generated
   */
  EReference getPlanning_Personlist();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.PersonTasks <em>Person Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person Tasks</em>'.
   * @see persons.tasks.taskDSL.PersonTasks
   * @generated
   */
  EClass getPersonTasks();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.PersonTasks#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks.taskDSL.PersonTasks#getName()
   * @see #getPersonTasks()
   * @generated
   */
  EAttribute getPersonTasks_Name();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks.taskDSL.PersonTasks#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see persons.tasks.taskDSL.PersonTasks#getTasks()
   * @see #getPersonTasks()
   * @generated
   */
  EReference getPersonTasks_Tasks();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see persons.tasks.taskDSL.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.Task#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see persons.tasks.taskDSL.Task#getAction()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Action();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Task#getPrio <em>Prio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prio</em>'.
   * @see persons.tasks.taskDSL.Task#getPrio()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Prio();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Task#getDl <em>Dl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dl</em>'.
   * @see persons.tasks.taskDSL.Task#getDl()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Dl();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Task#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see persons.tasks.taskDSL.Task#getUnit()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Unit();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see persons.tasks.taskDSL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.LunchAction <em>Lunch Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lunch Action</em>'.
   * @see persons.tasks.taskDSL.LunchAction
   * @generated
   */
  EClass getLunchAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.LunchAction#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see persons.tasks.taskDSL.LunchAction#getLocation()
   * @see #getLunchAction()
   * @generated
   */
  EAttribute getLunchAction_Location();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.MeetingAction <em>Meeting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meeting Action</em>'.
   * @see persons.tasks.taskDSL.MeetingAction
   * @generated
   */
  EClass getMeetingAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.MeetingAction#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see persons.tasks.taskDSL.MeetingAction#getTopic()
   * @see #getMeetingAction()
   * @generated
   */
  EAttribute getMeetingAction_Topic();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.PaperAction <em>Paper Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paper Action</em>'.
   * @see persons.tasks.taskDSL.PaperAction
   * @generated
   */
  EClass getPaperAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.PaperAction#getReport <em>Report</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Report</em>'.
   * @see persons.tasks.taskDSL.PaperAction#getReport()
   * @see #getPaperAction()
   * @generated
   */
  EAttribute getPaperAction_Report();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.PaymentAction <em>Payment Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payment Action</em>'.
   * @see persons.tasks.taskDSL.PaymentAction
   * @generated
   */
  EClass getPaymentAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.PaymentAction#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see persons.tasks.taskDSL.PaymentAction#getAmount()
   * @see #getPaymentAction()
   * @generated
   */
  EAttribute getPaymentAction_Amount();

  /**
   * Returns the meta object for enum '{@link persons.tasks.taskDSL.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Unit</em>'.
   * @see persons.tasks.taskDSL.TimeUnit
   * @generated
   */
  EEnum getTimeUnit();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TaskDSLFactory getTaskDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PlanningImpl <em>Planning</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PlanningImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPlanning()
     * @generated
     */
    EClass PLANNING = eINSTANCE.getPlanning();

    /**
     * The meta object literal for the '<em><b>Personlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLANNING__PERSONLIST = eINSTANCE.getPlanning_Personlist();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PersonTasksImpl <em>Person Tasks</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PersonTasksImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPersonTasks()
     * @generated
     */
    EClass PERSON_TASKS = eINSTANCE.getPersonTasks();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_TASKS__NAME = eINSTANCE.getPersonTasks_Name();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON_TASKS__TASKS = eINSTANCE.getPersonTasks_Tasks();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.TaskImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__ACTION = eINSTANCE.getTask_Action();

    /**
     * The meta object literal for the '<em><b>Prio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__PRIO = eINSTANCE.getTask_Prio();

    /**
     * The meta object literal for the '<em><b>Dl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DL = eINSTANCE.getTask_Dl();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__UNIT = eINSTANCE.getTask_Unit();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.LunchActionImpl <em>Lunch Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.LunchActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getLunchAction()
     * @generated
     */
    EClass LUNCH_ACTION = eINSTANCE.getLunchAction();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LUNCH_ACTION__LOCATION = eINSTANCE.getLunchAction_Location();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.MeetingActionImpl <em>Meeting Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.MeetingActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getMeetingAction()
     * @generated
     */
    EClass MEETING_ACTION = eINSTANCE.getMeetingAction();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEETING_ACTION__TOPIC = eINSTANCE.getMeetingAction_Topic();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PaperActionImpl <em>Paper Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PaperActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaperAction()
     * @generated
     */
    EClass PAPER_ACTION = eINSTANCE.getPaperAction();

    /**
     * The meta object literal for the '<em><b>Report</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAPER_ACTION__REPORT = eINSTANCE.getPaperAction_Report();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PaymentActionImpl <em>Payment Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PaymentActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaymentAction()
     * @generated
     */
    EClass PAYMENT_ACTION = eINSTANCE.getPaymentAction();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYMENT_ACTION__AMOUNT = eINSTANCE.getPaymentAction_Amount();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.TimeUnit <em>Time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.TimeUnit
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.getTimeUnit();

  }

} //TaskDSLPackage
