/*
 * generated by Xtext 2.40.0
 */
package gameOfLife.tasks.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTaskDSLScopeProvider extends DelegatingScopeProvider {
}
