/**
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GameOfLifeDSLIdeModule extends AbstractGameOfLifeDSLIdeModule {
}
