/*
 * generated by Xtext 2.40.0
 */
package gameoflife.dsl.serializer;

import com.google.inject.Inject;
import gameoflife.dsl.gameOfLifeDSL.BirthRule;
import gameoflife.dsl.gameOfLifeDSL.Cell;
import gameoflife.dsl.gameOfLifeDSL.GameOfLifeDSLPackage;
import gameoflife.dsl.gameOfLifeDSL.Grid;
import gameoflife.dsl.gameOfLifeDSL.Model;
import gameoflife.dsl.gameOfLifeDSL.NeighborCondition;
import gameoflife.dsl.gameOfLifeDSL.Range;
import gameoflife.dsl.gameOfLifeDSL.Rules;
import gameoflife.dsl.gameOfLifeDSL.SurviveRule;
import gameoflife.dsl.services.GameOfLifeDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class GameOfLifeDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GameOfLifeDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GameOfLifeDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GameOfLifeDSLPackage.BIRTH_RULE:
				sequence_BirthRule(context, (BirthRule) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.CELL:
				sequence_Cell(context, (Cell) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.GRID:
				sequence_Grid(context, (Grid) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.NEIGHBOR_CONDITION:
				sequence_NeighborCondition(context, (NeighborCondition) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.RANGE:
				sequence_Range(context, (Range) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.RULES:
				sequence_Rules(context, (Rules) semanticObject); 
				return; 
			case GameOfLifeDSLPackage.SURVIVE_RULE:
				sequence_SurviveRule(context, (SurviveRule) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     BirthRule returns BirthRule
	 *
	 * Constraint:
	 *     neighbors=NeighborCondition
	 * </pre>
	 */
	protected void sequence_BirthRule(ISerializationContext context, BirthRule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameOfLifeDSLPackage.Literals.BIRTH_RULE__NEIGHBORS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameOfLifeDSLPackage.Literals.BIRTH_RULE__NEIGHBORS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBirthRuleAccess().getNeighborsNeighborConditionParserRuleCall_2_0(), semanticObject.getNeighbors());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Cell returns Cell
	 *
	 * Constraint:
	 *     (x=INT y=INT)
	 * </pre>
	 */
	protected void sequence_Cell(ISerializationContext context, Cell semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameOfLifeDSLPackage.Literals.CELL__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameOfLifeDSLPackage.Literals.CELL__X));
			if (transientValues.isValueTransient(semanticObject, GameOfLifeDSLPackage.Literals.CELL__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameOfLifeDSLPackage.Literals.CELL__Y));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCellAccess().getXINTTerminalRuleCall_2_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getCellAccess().getYINTTerminalRuleCall_4_0(), semanticObject.getY());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Grid returns Grid
	 *
	 * Constraint:
	 *     (name=ID liveCells+=Cell*)
	 * </pre>
	 */
	protected void sequence_Grid(ISerializationContext context, Grid semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     ((grids+=Grid+ rules+=Rules) | rules+=Rules)?
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     NeighborCondition returns NeighborCondition
	 *
	 * Constraint:
	 *     (count=INT | range=Range)
	 * </pre>
	 */
	protected void sequence_NeighborCondition(ISerializationContext context, NeighborCondition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Range returns Range
	 *
	 * Constraint:
	 *     (min=INT max=INT)
	 * </pre>
	 */
	protected void sequence_Range(ISerializationContext context, Range semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameOfLifeDSLPackage.Literals.RANGE__MIN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameOfLifeDSLPackage.Literals.RANGE__MIN));
			if (transientValues.isValueTransient(semanticObject, GameOfLifeDSLPackage.Literals.RANGE__MAX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameOfLifeDSLPackage.Literals.RANGE__MAX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRangeAccess().getMinINTTerminalRuleCall_1_0(), semanticObject.getMin());
		feeder.accept(grammarAccess.getRangeAccess().getMaxINTTerminalRuleCall_3_0(), semanticObject.getMax());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rules returns Rules
	 *
	 * Constraint:
	 *     ((surviveRules+=SurviveRule+ birthRules+=BirthRule+) | birthRules+=BirthRule+)?
	 * </pre>
	 */
	protected void sequence_Rules(ISerializationContext context, Rules semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SurviveRule returns SurviveRule
	 *
	 * Constraint:
	 *     neighbors=NeighborCondition
	 * </pre>
	 */
	protected void sequence_SurviveRule(ISerializationContext context, SurviveRule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameOfLifeDSLPackage.Literals.SURVIVE_RULE__NEIGHBORS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameOfLifeDSLPackage.Literals.SURVIVE_RULE__NEIGHBORS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSurviveRuleAccess().getNeighborsNeighborConditionParserRuleCall_2_0(), semanticObject.getNeighbors());
		feeder.finish();
	}
	
	
}
